{% set version = "0.10.0" %}
{% set name = "bluesky-kafka" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5aab55d4d47261327d0ab6c7f76d2b079f93f625917ee118dd9e638b94f1929f

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - bluesky-base
    - msgpack-python
    - msgpack-numpy
    - python-confluent-kafka
    - suitcase-mongo

test:
  requires:
    - python {{ python_min }}
  imports:
    - bluesky_kafka

about:
  home: https://github.com/bluesky/bluesky-kafka
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The bluesky-kafka module
  dev_url: https://github.com/bluesky/bluesky-kafka

extra:
  recipe-maintainers:
    - conda-forge/event-model
    - jklynch
    - mrakitin
